/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package dgmpp;

public class AttributesMap {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AttributesMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AttributesMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dgmppJNI.delete_AttributesMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AttributesMap() {
    this(dgmppJNI.new_AttributesMap__SWIG_0(), true);
  }

  public AttributesMap(AttributesMap arg0) {
    this(dgmppJNI.new_AttributesMap__SWIG_1(AttributesMap.getCPtr(arg0), arg0), true);
  }

  public long size() {
    return dgmppJNI.AttributesMap_size(swigCPtr, this);
  }

  public boolean empty() {
    return dgmppJNI.AttributesMap_empty(swigCPtr, this);
  }

  public void clear() {
    dgmppJNI.AttributesMap_clear(swigCPtr, this);
  }

  public Attribute get(int key) {
    long cPtr = dgmppJNI.AttributesMap_get(swigCPtr, this, key);
    return (cPtr == 0) ? null : new Attribute(cPtr, true);
  }

  public void set(int key, Attribute x) {
    dgmppJNI.AttributesMap_set(swigCPtr, this, key, Attribute.getCPtr(x), x);
  }

  public void del(int key) {
    dgmppJNI.AttributesMap_del(swigCPtr, this, key);
  }

  public boolean has_key(int key) {
    return dgmppJNI.AttributesMap_has_key(swigCPtr, this, key);
  }

}
