/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package dgmpp;

public class BoostersList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BoostersList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BoostersList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dgmppJNI.delete_BoostersList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BoostersList() {
    this(dgmppJNI.new_BoostersList__SWIG_0(), true);
  }

  public BoostersList(long n) {
    this(dgmppJNI.new_BoostersList__SWIG_1(n), true);
  }

  public long size() {
    return dgmppJNI.BoostersList_size(swigCPtr, this);
  }

  public long capacity() {
    return dgmppJNI.BoostersList_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    dgmppJNI.BoostersList_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return dgmppJNI.BoostersList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    dgmppJNI.BoostersList_clear(swigCPtr, this);
  }

  public void add(Booster x) {
    dgmppJNI.BoostersList_add(swigCPtr, this, Booster.getCPtr(x), x);
  }

  public Booster get(int i) {
    long cPtr = dgmppJNI.BoostersList_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Booster(cPtr, true);
  }

  public void set(int i, Booster val) {
    dgmppJNI.BoostersList_set(swigCPtr, this, i, Booster.getCPtr(val), val);
  }

}
