/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package dgmpp;

public class CargoList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CargoList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CargoList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dgmppJNI.delete_CargoList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CargoList() {
    this(dgmppJNI.new_CargoList__SWIG_0(), true);
  }

  public CargoList(long n) {
    this(dgmppJNI.new_CargoList__SWIG_1(n), true);
  }

  public long size() {
    return dgmppJNI.CargoList_size(swigCPtr, this);
  }

  public long capacity() {
    return dgmppJNI.CargoList_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    dgmppJNI.CargoList_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return dgmppJNI.CargoList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    dgmppJNI.CargoList_clear(swigCPtr, this);
  }

  public void add(Cargo x) {
    dgmppJNI.CargoList_add(swigCPtr, this, Cargo.getCPtr(x), x);
  }

  public Cargo get(int i) {
    long cPtr = dgmppJNI.CargoList_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Cargo(cPtr, true);
  }

  public void set(int i, Cargo val) {
    dgmppJNI.CargoList_set(swigCPtr, this, i, Cargo.getCPtr(val), val);
  }

}
