/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package dgmpp;

public class ControlTower extends Item {
  private transient long swigCPtr;
  private boolean swigCMemOwnDerived;

  protected ControlTower(long cPtr, boolean cMemoryOwn) {
    super(dgmppJNI.ControlTower_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ControlTower obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        dgmppJNI.delete_ControlTower(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public StarbaseStructure addStructure(int typeID) {
    long cPtr = dgmppJNI.ControlTower_addStructure(swigCPtr, this, typeID);
    return (cPtr == 0) ? null : new StarbaseStructure(cPtr, true);
  }

  public void removeStructure(StarbaseStructure structure) {
    dgmppJNI.ControlTower_removeStructure(swigCPtr, this, StarbaseStructure.getCPtr(structure), structure);
  }

  public StarbaseStructuresList getStructures() {
    return new StarbaseStructuresList(dgmppJNI.ControlTower_getStructures(swigCPtr, this), true);
  }

  public DamagePattern getDamagePattern() {
    return new DamagePattern(dgmppJNI.ControlTower_getDamagePattern(swigCPtr, this), false);
  }

  public void setDamagePattern(DamagePattern damagePattern) {
    dgmppJNI.ControlTower_setDamagePattern(swigCPtr, this, DamagePattern.getCPtr(damagePattern), damagePattern);
  }

  public float getPowerGridUsed() {
    return dgmppJNI.ControlTower_getPowerGridUsed(swigCPtr, this);
  }

  public float getTotalPowerGrid() {
    return dgmppJNI.ControlTower_getTotalPowerGrid(swigCPtr, this);
  }

  public float getCpuUsed() {
    return dgmppJNI.ControlTower_getCpuUsed(swigCPtr, this);
  }

  public float getTotalCpu() {
    return dgmppJNI.ControlTower_getTotalCpu(swigCPtr, this);
  }

  public Resistances getResistances() {
    return new Resistances(dgmppJNI.ControlTower_getResistances(swigCPtr, this), false);
  }

  public Tank getTank() {
    return new Tank(dgmppJNI.ControlTower_getTank(swigCPtr, this), false);
  }

  public Tank getEffectiveTank() {
    return new Tank(dgmppJNI.ControlTower_getEffectiveTank(swigCPtr, this), false);
  }

  public HitPoints getHitPoints() {
    return new HitPoints(dgmppJNI.ControlTower_getHitPoints(swigCPtr, this), false);
  }

  public HitPoints getEffectiveHitPoints() {
    return new HitPoints(dgmppJNI.ControlTower_getEffectiveHitPoints(swigCPtr, this), false);
  }

  public float getShieldRecharge() {
    return dgmppJNI.ControlTower_getShieldRecharge(swigCPtr, this);
  }

  public float getWeaponDps() {
    return dgmppJNI.ControlTower_getWeaponDps(swigCPtr, this);
  }

  public float getWeaponVolley() {
    return dgmppJNI.ControlTower_getWeaponVolley(swigCPtr, this);
  }

}
