/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package dgmpp;

public class DamageVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DamageVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DamageVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dgmppJNI.delete_DamageVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DamageVector(float value) {
    this(dgmppJNI.new_DamageVector__SWIG_0(value), true);
  }

  public DamageVector() {
    this(dgmppJNI.new_DamageVector__SWIG_1(), true);
  }

  public DamageVector(float em, float thermal, float kinetic, float explosive) {
    this(dgmppJNI.new_DamageVector__SWIG_2(em, thermal, kinetic, explosive), true);
  }

  public void setEmAmount(float value) {
    dgmppJNI.DamageVector_emAmount_set(swigCPtr, this, value);
  }

  public float getEmAmount() {
    return dgmppJNI.DamageVector_emAmount_get(swigCPtr, this);
  }

  public void setThermalAmount(float value) {
    dgmppJNI.DamageVector_thermalAmount_set(swigCPtr, this, value);
  }

  public float getThermalAmount() {
    return dgmppJNI.DamageVector_thermalAmount_get(swigCPtr, this);
  }

  public void setKineticAmount(float value) {
    dgmppJNI.DamageVector_kineticAmount_set(swigCPtr, this, value);
  }

  public float getKineticAmount() {
    return dgmppJNI.DamageVector_kineticAmount_get(swigCPtr, this);
  }

  public void setExplosiveAmount(float value) {
    dgmppJNI.DamageVector_explosiveAmount_set(swigCPtr, this, value);
  }

  public float getExplosiveAmount() {
    return dgmppJNI.DamageVector_explosiveAmount_get(swigCPtr, this);
  }

  public float total() {
    return dgmppJNI.DamageVector_total(swigCPtr, this);
  }

}
