/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package dgmpp;

public class Engine {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected Engine(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Engine obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dgmppJNI.delete_Engine(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Engine(SqlConnector sqlConnector) {
    this(dgmppJNI.new_Engine(SqlConnector.getCPtr(sqlConnector), sqlConnector), true);
  }

  public Area setArea(int typeID) {
    long cPtr = dgmppJNI.Engine_setArea(swigCPtr, this, typeID);
    return (cPtr == 0) ? null : new Area(cPtr, true);
  }

  public ControlTower setControlTower(int typeID) {
    long cPtr = dgmppJNI.Engine_setControlTower(swigCPtr, this, typeID);
    return (cPtr == 0) ? null : new ControlTower(cPtr, true);
  }

  public void clearArea() {
    dgmppJNI.Engine_clearArea(swigCPtr, this);
  }

  public Gang getGang() {
    long cPtr = dgmppJNI.Engine_getGang(swigCPtr, this);
    return (cPtr == 0) ? null : new Gang(cPtr, true);
  }

  public Area getArea() {
    long cPtr = dgmppJNI.Engine_getArea(swigCPtr, this);
    return (cPtr == 0) ? null : new Area(cPtr, true);
  }

  public ControlTower getControlTower() {
    long cPtr = dgmppJNI.Engine_getControlTower(swigCPtr, this);
    return (cPtr == 0) ? null : new ControlTower(cPtr, true);
  }

}
