/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package dgmpp;

public class Gang extends Item {
  private transient long swigCPtr;
  private boolean swigCMemOwnDerived;

  protected Gang(long cPtr, boolean cMemoryOwn) {
    super(dgmppJNI.Gang_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Gang obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        dgmppJNI.delete_Gang(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public CharactersList getPilots() {
    return new CharactersList(dgmppJNI.Gang_getPilots(swigCPtr, this), true);
  }

  public Character addPilot() {
    long cPtr = dgmppJNI.Gang_addPilot(swigCPtr, this);
    return (cPtr == 0) ? null : new Character(cPtr, true);
  }

  public void removePilot(Character character) {
    dgmppJNI.Gang_removePilot(swigCPtr, this, Character.getCPtr(character), character);
  }

  public Character getFleetBooster() {
    long cPtr = dgmppJNI.Gang_getFleetBooster(swigCPtr, this);
    return (cPtr == 0) ? null : new Character(cPtr, true);
  }

  public Character getWingBooster() {
    long cPtr = dgmppJNI.Gang_getWingBooster(swigCPtr, this);
    return (cPtr == 0) ? null : new Character(cPtr, true);
  }

  public Character getSquadBooster() {
    long cPtr = dgmppJNI.Gang_getSquadBooster(swigCPtr, this);
    return (cPtr == 0) ? null : new Character(cPtr, true);
  }

  public void setFleetBooster(Character fleetBooster) {
    dgmppJNI.Gang_setFleetBooster(swigCPtr, this, Character.getCPtr(fleetBooster), fleetBooster);
  }

  public void setWingBooster(Character wingBooster) {
    dgmppJNI.Gang_setWingBooster(swigCPtr, this, Character.getCPtr(wingBooster), wingBooster);
  }

  public void setSquadBooster(Character squadBooster) {
    dgmppJNI.Gang_setSquadBooster(swigCPtr, this, Character.getCPtr(squadBooster), squadBooster);
  }

  public void removeFleetBooster() {
    dgmppJNI.Gang_removeFleetBooster(swigCPtr, this);
  }

  public void removeWingBooster() {
    dgmppJNI.Gang_removeWingBooster(swigCPtr, this);
  }

  public void removeSquadBooster() {
    dgmppJNI.Gang_removeSquadBooster(swigCPtr, this);
  }

}
