/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package dgmpp;

public class Item {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected Item(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Item obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dgmppJNI.delete_Item(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Engine getEngine() {
    long cPtr = dgmppJNI.Item_getEngine(swigCPtr, this);
    return (cPtr == 0) ? null : new Engine(cPtr, true);
  }

  public Item getOwner() {
    long cPtr = dgmppJNI.Item_getOwner(swigCPtr, this);
    return (cPtr == 0) ? null : new Item(cPtr, true);
  }

  public int getTypeID() {
    return dgmppJNI.Item_getTypeID(swigCPtr, this);
  }

  public int getGroupID() {
    return dgmppJNI.Item_getGroupID(swigCPtr, this);
  }

  public int getCategoryID() {
    return dgmppJNI.Item_getCategoryID(swigCPtr, this);
  }

  public Attribute getAttribute(int attributeID) {
    long cPtr = dgmppJNI.Item_getAttribute(swigCPtr, this, attributeID);
    return (cPtr == 0) ? null : new Attribute(cPtr, true);
  }

  public AttributesMap getAttributes() {
    return new AttributesMap(dgmppJNI.Item_getAttributes(swigCPtr, this), false);
  }

  public boolean hasAttribute(int attributeID) {
    return dgmppJNI.Item_hasAttribute(swigCPtr, this, attributeID);
  }

  public Effect getEffect(int effectID) {
    long cPtr = dgmppJNI.Item_getEffect(swigCPtr, this, effectID);
    return (cPtr == 0) ? null : new Effect(cPtr, true);
  }

  public boolean requireSkill(int skillID) {
    return dgmppJNI.Item_requireSkill(swigCPtr, this, skillID);
  }

  public boolean hasEffect(int effectID) {
    return dgmppJNI.Item_hasEffect(swigCPtr, this, effectID);
  }

  public String getTypeName() {
    return dgmppJNI.Item_getTypeName(swigCPtr, this);
  }

}
