/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package dgmpp;

public class ModulesList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ModulesList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ModulesList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dgmppJNI.delete_ModulesList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ModulesList() {
    this(dgmppJNI.new_ModulesList__SWIG_0(), true);
  }

  public ModulesList(long n) {
    this(dgmppJNI.new_ModulesList__SWIG_1(n), true);
  }

  public long size() {
    return dgmppJNI.ModulesList_size(swigCPtr, this);
  }

  public long capacity() {
    return dgmppJNI.ModulesList_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    dgmppJNI.ModulesList_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return dgmppJNI.ModulesList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    dgmppJNI.ModulesList_clear(swigCPtr, this);
  }

  public void add(Module x) {
    dgmppJNI.ModulesList_add(swigCPtr, this, Module.getCPtr(x), x);
  }

  public Module get(int i) {
    long cPtr = dgmppJNI.ModulesList_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Module(cPtr, true);
  }

  public void set(int i, Module val) {
    dgmppJNI.ModulesList_set(swigCPtr, this, i, Module.getCPtr(val), val);
  }

}
