/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package dgmpp;

public class Skill extends Item {
  private transient long swigCPtr;
  private boolean swigCMemOwnDerived;

  protected Skill(long cPtr, boolean cMemoryOwn) {
    super(dgmppJNI.Skill_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Skill obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        dgmppJNI.delete_Skill(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public boolean isLearned() {
    return dgmppJNI.Skill_isLearned(swigCPtr, this);
  }

  public int getSkillLevel() {
    return dgmppJNI.Skill_getSkillLevel(swigCPtr, this);
  }

}
