/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package dgmpp;

public class SkillsMap {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SkillsMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SkillsMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dgmppJNI.delete_SkillsMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SkillsMap() {
    this(dgmppJNI.new_SkillsMap__SWIG_0(), true);
  }

  public SkillsMap(SkillsMap arg0) {
    this(dgmppJNI.new_SkillsMap__SWIG_1(SkillsMap.getCPtr(arg0), arg0), true);
  }

  public long size() {
    return dgmppJNI.SkillsMap_size(swigCPtr, this);
  }

  public boolean empty() {
    return dgmppJNI.SkillsMap_empty(swigCPtr, this);
  }

  public void clear() {
    dgmppJNI.SkillsMap_clear(swigCPtr, this);
  }

  public Skill get(int key) {
    long cPtr = dgmppJNI.SkillsMap_get(swigCPtr, this, key);
    return (cPtr == 0) ? null : new Skill(cPtr, true);
  }

  public void set(int key, Skill x) {
    dgmppJNI.SkillsMap_set(swigCPtr, this, key, Skill.getCPtr(x), x);
  }

  public void del(int key) {
    dgmppJNI.SkillsMap_del(swigCPtr, this, key);
  }

  public boolean has_key(int key) {
    return dgmppJNI.SkillsMap_has_key(swigCPtr, this, key);
  }

}
