/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package dgmpp;

public class StarbaseStructuresList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StarbaseStructuresList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StarbaseStructuresList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dgmppJNI.delete_StarbaseStructuresList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StarbaseStructuresList() {
    this(dgmppJNI.new_StarbaseStructuresList__SWIG_0(), true);
  }

  public StarbaseStructuresList(long n) {
    this(dgmppJNI.new_StarbaseStructuresList__SWIG_1(n), true);
  }

  public long size() {
    return dgmppJNI.StarbaseStructuresList_size(swigCPtr, this);
  }

  public long capacity() {
    return dgmppJNI.StarbaseStructuresList_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    dgmppJNI.StarbaseStructuresList_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return dgmppJNI.StarbaseStructuresList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    dgmppJNI.StarbaseStructuresList_clear(swigCPtr, this);
  }

  public void add(StarbaseStructure x) {
    dgmppJNI.StarbaseStructuresList_add(swigCPtr, this, StarbaseStructure.getCPtr(x), x);
  }

  public StarbaseStructure get(int i) {
    long cPtr = dgmppJNI.StarbaseStructuresList_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new StarbaseStructure(cPtr, true);
  }

  public void set(int i, StarbaseStructure val) {
    dgmppJNI.StarbaseStructuresList_set(swigCPtr, this, i, StarbaseStructure.getCPtr(val), val);
  }

}
