/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package dgmpp;

public class StarbaseStructure extends Module {
  private transient long swigCPtr;
  private boolean swigCMemOwnDerived;

  protected StarbaseStructure(long cPtr, boolean cMemoryOwn) {
    super(dgmppJNI.StarbaseStructure_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StarbaseStructure obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        dgmppJNI.delete_StarbaseStructure(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Resistances getResistances() {
    return new Resistances(dgmppJNI.StarbaseStructure_getResistances(swigCPtr, this), false);
  }

  public Tank getTank() {
    return new Tank(dgmppJNI.StarbaseStructure_getTank(swigCPtr, this), false);
  }

  public Tank getEffectiveTank() {
    return new Tank(dgmppJNI.StarbaseStructure_getEffectiveTank(swigCPtr, this), false);
  }

  public HitPoints getHitPoints() {
    return new HitPoints(dgmppJNI.StarbaseStructure_getHitPoints(swigCPtr, this), false);
  }

  public HitPoints getEffectiveHitPoints() {
    return new HitPoints(dgmppJNI.StarbaseStructure_getEffectiveHitPoints(swigCPtr, this), false);
  }

  public float getShieldRecharge() {
    return dgmppJNI.StarbaseStructure_getShieldRecharge(swigCPtr, this);
  }

}
